import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const output = path.join(root, "src", "environment-catalog.js");
const models = {
  "industrial/building-h": "assets/environments/kenney/industrial/building-h.glb",
  "industrial/building-k": "assets/environments/kenney/industrial/building-k.glb",
  "industrial/chimney-large": "assets/environments/kenney/industrial/chimney-large.glb",
  "industrial/detail-tank": "assets/environments/kenney/industrial/detail-tank.glb",
  "space/cables": "assets/environments/kenney/space/cables.glb",
  "space/gate": "assets/environments/kenney/space/gate.glb",
  "space/template-detail": "assets/environments/kenney/space/template-detail.glb",
  "space/template-wall": "assets/environments/kenney/space/template-wall.glb",
  "space/template-wall-corner": "assets/environments/kenney/space/template-wall-corner.glb",
  "space/template-wall-detail-a": "assets/environments/kenney/space/template-wall-detail-a.glb",
  "space/template-wall-half": "assets/environments/kenney/space/template-wall-half.glb",
  "cave/gate-rock": "assets/environments/kenney/cave/gate-rock.glb",
  "cave/template-detail": "assets/environments/kenney/cave/template-detail.glb",
  "cave/template-floor-layer": "assets/environments/kenney/cave/template-floor-layer.glb",
  "cave/template-wall": "assets/environments/kenney/cave/template-wall.glb",
  "cave/template-wall-corner": "assets/environments/kenney/cave/template-wall-corner.glb",
  "cave/template-wall-detail-a": "assets/environments/kenney/cave/template-wall-detail-a.glb",
  "cave/template-wall-half": "assets/environments/kenney/cave/template-wall-half.glb"
};
const texturePaths = {
  industrial: "assets/environments/kenney/industrial/colormap.png",
  space: "assets/environments/kenney/space/colormap.png",
  cave: "assets/environments/kenney/cave/colormap.png"
};

const catalog = {};
for (const [id, relativePath] of Object.entries(models)) {
  const absolutePath = path.join(root, relativePath);
  if (!fs.existsSync(absolutePath)) {
    throw new Error(`Missing environment asset: ${relativePath}`);
  }
  const data = fs.readFileSync(absolutePath);
  catalog[id] = {
    path: relativePath,
    bytes: data.byteLength,
    data: data.toString("base64")
  };
}

const textures = {};
for (const [pack, relativePath] of Object.entries(texturePaths)) {
  const absolutePath = path.join(root, relativePath);
  if (!fs.existsSync(absolutePath)) {
    throw new Error(`Missing environment texture: ${relativePath}`);
  }
  const data = fs.readFileSync(absolutePath);
  textures[pack] = {
    path: relativePath,
    bytes: data.byteLength,
    data: `data:image/png;base64,${data.toString("base64")}`
  };
}

const source = `/* Generated by scripts/environment-catalog.mjs. Do not edit by hand. */
window.CS3D_ENV_CATALOG=${JSON.stringify({ version: 1, models: catalog, textures })};
`;
fs.writeFileSync(output, source);

const bytes = [...Object.values(catalog), ...Object.values(textures)]
  .reduce((total, entry) => total + entry.bytes, 0);
console.log(
  `Packed ${Object.keys(catalog).length} offline GLBs + ${Object.keys(textures).length} textures -> ${path.relative(root, output)} (${(bytes / 1024).toFixed(0)} kB source assets)`
);
