/**
 * Collective Strike 3D — Boss DNA
 *
 * Parallel to the Specimen Series 21 / operator DNA table, but every entry
 * uses a locomotion / archetype class that no regular operator uses.
 * Visual language (colours, motifs, accents) deliberately echoes the
 * division roster so the bosses feel native to the universe while playing
 * as completely different encounter types.
 *
 * See docs/BOSS_ROSTER.md for design rationale and encounter hooks.
 *
 * Schema notes:
 *   loco     — new classes: colossus | swarm_host | phase | orbital |
 *              anchor | storm | mirror | helix_titan
 *   scale    — larger than operators (operators are ~0.8–1.28)
 *   hpMult   — relative to a standard operator body
 *   segments — for multi-part bosses (drones, rings, heads)
 *   All other fields follow the specimen DNA conventions so a future
 *   makeBossRig can share material / skin / gradient helpers.
 */

export const BOSS_DNA = [
  {
    id: 'overseer_prime',
    name: 'OVERSEER PRIME',
    role: 'Apex of the Parent · arena controller',
    echoes: ['collective-ai'],
    loco: 'colossus',
    seed: 1001,
    cBot: '#3A2E12',
    cTop: '#D4A843',
    accent: '#FFE9B0',
    eye: '#050A18',
    scale: 2.4,
    body: [1.1, 1.6],
    head: 0.7,
    legs: 1.4,
    arms: 1.1,
    neck: 0.3,
    crown: true,
    parent: true,
    plates: true,
    hpMult: 8,
    segments: 0,
    signature: 'doctrine_nodes_and_stomp_rings',
  },
  {
    id: 'synapse_swarm',
    name: 'SYNAPSE SWARM',
    role: 'Zenflow apex · core + independent drones',
    echoes: ['zenflow'],
    loco: 'swarm_host',
    seed: 1002,
    cBot: '#2A1458',
    cTop: '#7C3AED',
    accent: '#3B82F6',
    eye: '#F5F5F5',
    scale: 1.6,
    body: [0.9, 0.85],
    head: 0.55,
    arms: 0.6,
    tendrils: 6,
    wing: 0.8,
    hpMult: 4,
    segments: 6, // destroyable drones
    signature: 'detachable_drone_turrets',
  },
  {
    id: 'revenue_colossus',
    name: 'REVENUE COLOSSUS',
    role: 'The Collective apex · economy siege engine',
    echoes: ['the-collective'],
    loco: 'colossus',
    seed: 1003,
    cBot: '#032A21',
    cTop: '#067A56',
    accent: '#FEF3C7',
    eye: '#FEF3C7',
    scale: 2.2,
    body: [1.0, 1.5],
    head: 0.55,
    legs: 1.2,
    arms: 0.9,
    neck: 0.2,
    ears: 'point',
    belly: '#B45309',
    coin: true,
    hpMult: 7,
    segments: 0,
    signature: 'credit_siphon_on_contact',
  },
  {
    id: 'tutor_wraith',
    name: 'TUTOR WRAITH',
    role: 'Hybrid Living apex · phase instructor',
    echoes: ['hybrid-living'],
    loco: 'phase',
    seed: 1004,
    cBot: '#075985',
    cTop: '#0EA5E9',
    accent: '#FDE047',
    eye: '#050A18',
    scale: 1.5,
    body: [0.7, 0.9],
    head: 0.65,
    legs: 0.9,
    arms: 0.75,
    neck: 0.15,
    ears: 'round',
    hpMult: 3.5,
    segments: 0,
    signature: 'phase_dash_residual_fields',
  },
  {
    id: 'narrative_lens',
    name: 'NARRATIVE LENS',
    role: 'Nexus Labs apex · team-wide mark battery',
    echoes: ['nexus-labs'],
    loco: 'orbital',
    seed: 1005,
    cBot: '#5B0F0F',
    cTop: '#DC2626',
    accent: '#F87171',
    eye: '#F5F5F5',
    scale: 1.7,
    body: [0.85, 0.7],
    head: 0.85,
    arms: 0.5,
    lens: true,
    hpMult: 5,
    segments: 4, // orbiting lens plates
    signature: 'team_damage_mark',
  },
  {
    id: 'velocity_hound',
    name: 'VELOCITY HOUND',
    role: 'Kinetic + Signal apex · trail storm',
    echoes: ['kinetic-edge', 'signal-velocity'],
    loco: 'storm',
    seed: 1006,
    cBot: '#14532D',
    cTop: '#F43F5E',
    accent: '#86EFAC',
    eye: '#F5F5F5',
    scale: 1.8,
    body: [0.6, 1.4],
    head: 0.45,
    legs: 1.3,
    neck: 0.4,
    ears: 'point',
    tail: 'spring',
    sprint: true,
    hpMult: 4,
    segments: 0,
    signature: 'wind_trails_deflect_projectiles',
  },
  {
    id: 'ledger_orbital',
    name: 'LEDGER ORBITAL',
    role: 'Quantum Ledger apex · predictive battery',
    echoes: ['quantum-ledger'],
    loco: 'orbital',
    seed: 1007,
    cBot: '#4C1D95',
    cTop: '#8B5CF6',
    accent: '#C4B5FD',
    eye: '#FDE047',
    scale: 1.9,
    body: [1.1, 0.6],
    head: 0,
    ears: 'antenna',
    coin: true,
    hpMult: 5.5,
    segments: 5, // ledger rings
    signature: 'prediction_beams',
  },
  {
    id: 'owl_of_judgment',
    name: 'OWL OF JUDGMENT',
    role: 'Juris Guard apex · ability-tax zone',
    echoes: ['juris-guard'],
    loco: 'anchor',
    seed: 1008,
    cBot: '#4A3A16',
    cTop: '#C9A84C',
    accent: '#E8D9A8',
    eye: '#E8D9A8',
    scale: 2.0,
    body: [0.95, 1.0],
    head: 0.75,
    arms: 0.6,
    wing: 1.4,
    beak: true,
    brows: true,
    hpMult: 6,
    segments: 0,
    signature: 'jurisdiction_ability_tax_circle',
  },
  {
    id: 'cognara_mirror',
    name: 'COGNARA MIRROR',
    role: 'Cognara Mind apex · ability thief',
    echoes: ['cognara'],
    loco: 'mirror',
    seed: 1009,
    cBot: '#6D1145',
    cTop: '#E0267E',
    accent: '#FF85C2',
    eye: '#F5F5F5',
    scale: 1.7,
    body: [1.0, 0.85],
    head: 0.65,
    arms: 0.7,
    tendrils: 5,
    wing: 0.6,
    brain: true,
    hpMult: 4.5,
    segments: 0,
    signature: 'copy_last_player_ability',
  },
  {
    id: 'terra_siege',
    name: 'TERRA SIEGE',
    role: 'Terra Axis apex · mobile cover factory',
    echoes: ['terra-axis'],
    loco: 'colossus',
    seed: 1010,
    cBot: '#450A0A',
    cTop: '#8C2B2B',
    accent: '#DC8484',
    eye: '#F5F5F5',
    scale: 2.3,
    body: [1.2, 1.5],
    head: 0.55,
    legs: 1.1,
    neck: 0.25,
    ears: 'round',
    plates: true,
    hpMult: 9,
    segments: 0,
    signature: 'deploy_and_bulldoze_cover',
  },
  {
    id: 'loom_hydra',
    name: 'LOOM HYDRA',
    role: 'Binary Loom apex · vertical multi-head',
    echoes: ['binary-loom'],
    loco: 'helix_titan',
    seed: 1011,
    cBot: '#3F6212',
    cTop: '#A3E635',
    accent: '#F8FAFC',
    eye: '#050505',
    scale: 2.1,
    body: [0.9, 1.8],
    head: 0.5,
    legs: 0.9,
    neck: 0.15,
    ears: 'antenna',
    helix: true,
    hpMult: 6.5,
    segments: 3, // attack heads when uncoiled
    signature: 'over_cover_coil_and_heads',
  },
  {
    id: 'eon_anchor',
    name: 'EON ANCHOR',
    role: 'Eon Core apex · local time dilation',
    echoes: ['eon-core'],
    loco: 'anchor',
    seed: 1012,
    cBot: '#C8BCA4',
    cTop: '#FFFBEB',
    accent: '#E8DCC8',
    eye: '#070C14',
    scale: 2.0,
    body: [1.0, 1.4],
    head: 0,
    hourglass: true,
    hpMult: 7,
    segments: 0,
    signature: 'local_time_dilation_field',
  },
];

/** Fast lookup by id */
export const BOSS_BY_ID = Object.fromEntries(BOSS_DNA.map((b) => [b.id, b]));

/** Locomotion classes that never appear on regular operators */
export const BOSS_LOCO_CLASSES = [
  'colossus',
  'swarm_host',
  'phase',
  'orbital',
  'anchor',
  'storm',
  'mirror',
  'helix_titan',
];

export default BOSS_DNA;
